# Generated by Django 5.2.7 on 2026-06-06 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membershipplan_options_and_more'),
        ('payments', '0002_invoice_pending_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='membership_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_by_plan', to='memberships.membershipplan'),
        ),
    ]
