# Generated by Django 5.2.7 on 2026-05-13 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Task Lock',
                'verbose_name_plural': 'Task Locks',
            },
        ),
        migrations.CreateModel(
            name='AsyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(db_index=True, max_length=128)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=256, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('retried', 'Retried')], db_index=True, default='pending', max_length=20)),
                ('enqueued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=256, null=True, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Async Task',
                'verbose_name_plural': 'Async Tasks',
                'ordering': ['-enqueued_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=20)),
                ('message', models.TextField()),
                ('exception_type', models.CharField(blank=True, max_length=128)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('async_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='core.asynctask')),
            ],
            options={
                'verbose_name': 'Task Error',
                'verbose_name_plural': 'Task Errors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='asynctask',
            index=models.Index(fields=['status', 'enqueued_at'], name='core_asynct_status_15bcb7_idx'),
        ),
        migrations.AddIndex(
            model_name='asynctask',
            index=models.Index(fields=['task_type', 'status'], name='core_asynct_task_ty_9373ef_idx'),
        ),
    ]
