# Generated by Django 5.2.7 on 2026-05-25 10:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GymIssuedID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member'), ('staff', 'Staff')], max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_issued_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gym Issued ID',
                'verbose_name_plural': 'Gym Issued IDs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member'), ('staff', 'Staff')], max_length=10)),
                ('unique_id', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='^\\+?\\d{7,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('desired_login_id', models.CharField(max_length=32, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('whatsapp_notified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup_request', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_signup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signup Request',
                'verbose_name_plural': 'Signup Requests',
                'ordering': ['-submitted_at'],
                'unique_together': {('desired_login_id', 'phone_number')},
            },
        ),
    ]
