# Generated by Django 5.2.7 on 2026-05-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['duration_days', 'cardio_included'], 'verbose_name': 'Membership Plan', 'verbose_name_plural': 'Membership Plans'},
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='cardio_included',
            field=models.BooleanField(default=False),
        ),
    ]
