# Generated by Django 5.2.7 on 2026-06-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membershipplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='serial_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
