# Generated by Django 5.2.7 on 2026-07-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membership_payment_status_membership_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='final_amount',
            new_name='price_before_discount',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='membership_amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='membership',
            name='entry_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
