# Generated by Django 5.2.7 on 2026-07-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_rename_final_amount_membership_price_before_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-start_date', '-created_at'], 'verbose_name': 'Membership Fee Record', 'verbose_name_plural': 'Membership Fee Records'},
        ),
        migrations.RemoveField(
            model_name='membership',
            name='renewed_from',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='membership',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='entry_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Fully Paid'), ('partial', 'Partially Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
