# Generated by Django 5.2.7 on 2026-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='device_user_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
