# Generated by Django 5.2.7 on 2026-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_created_by_member_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='device_user_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
