# Generated by Django 5.2.7 on 2026-06-10 10:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_device_user_id_member_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
