# Generated by Django 5.2.7 on 2026-07-03 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='vehicle_number_permanent',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='vehicle_number_temporary',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='member',
            name='device_user_id',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
