# Generated by Django 5.2.7 on 2026-05-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='device_user_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
