# Generated by Django 5.2.7 on 2026-06-10 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancelog_device_user_id'),
        ('members', '0003_alter_member_device_user_id'),
        ('staffs', '0003_alter_staff_device_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=128)),
                ('device_type', models.CharField(choices=[('unknown', 'Unknown'), ('mb20', 'MB20'), ('aiface', 'AiFace')], default='unknown', max_length=32)),
                ('firmware_version', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_known_ip', models.CharField(blank=True, max_length=45)),
                ('last_payload', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Biometric Device',
                'verbose_name_plural': 'Biometric Devices',
            },
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='device_user_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='BiometricSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_type', models.CharField(blank=True, choices=[('member', 'Member'), ('staff', 'Staff')], max_length=12)),
                ('action', models.CharField(choices=[('device_heartbeat', 'Device Heartbeat'), ('access_attempt', 'Access Attempt'), ('enrollment', 'Enrollment'), ('device_sync', 'Device Sync'), ('conflict', 'Conflict')], max_length=32)),
                ('device_user_id', models.CharField(blank=True, max_length=64)),
                ('success', models.BooleanField(default=True)),
                ('payload', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='attendance.biometricdevice')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_sync_logs', to='members.member')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_sync_logs', to='staffs.staff')),
            ],
            options={
                'verbose_name': 'Biometric Sync Log',
                'verbose_name_plural': 'Biometric Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
