# Generated by Django 5.2.7 on 2026-06-10 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_biometricdevice'),
        ('attendance', '0003_attendancelog_device_user_id'),
        ('members', '0003_member_device_user_id_member_wallet_balance'),
        ('staffs', '0002_staff_device_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='device_type',
            field=models.CharField(
                choices=[('unknown', 'Unknown'), ('mb20', 'MB20'), ('aiface', 'AiFace')],
                default='unknown',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_known_ip',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='device_user_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='BiometricSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_type', models.CharField(blank=True, choices=[('member', 'Member'), ('staff', 'Staff')], max_length=12)),
                ('action', models.CharField(
                    choices=[
                        ('device_heartbeat', 'Device Heartbeat'),
                        ('access_attempt', 'Access Attempt'),
                        ('enrollment', 'Enrollment'),
                        ('device_sync', 'Device Sync'),
                        ('conflict', 'Conflict'),
                    ],
                    max_length=32,
                )),
                ('device_user_id', models.CharField(blank=True, max_length=64)),
                ('success', models.BooleanField(default=True)),
                ('payload', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sync_logs',
                    to='attendance.biometricdevice',
                )),
                ('member', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='biometric_sync_logs',
                    to='members.member',
                )),
                ('staff', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='biometric_sync_logs',
                    to='staffs.staff',
                )),
            ],
            options={
                'verbose_name': 'Biometric Sync Log',
                'verbose_name_plural': 'Biometric Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
