# Generated by Django 5.2.7 on 2026-06-12 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_biometricdevice_alter_attendancelog_device_user_id_and_more'),
        ('members', '0004_member_wallet_balance'),
        ('staffs', '0002_staff_device_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_type', models.CharField(blank=True, choices=[('member', 'Member'), ('staff', 'Staff')], max_length=12)),
                ('command', models.CharField(choices=[('sync_user', 'Sync User'), ('delete_user', 'Delete User'), ('enable_user', 'Enable User'), ('disable_user', 'Disable User'), ('refresh_user', 'Refresh User'), ('sync_face', 'Sync Face'), ('sync_fingerprint', 'Sync Fingerprint'), ('sync_password', 'Sync Password')], max_length=32)),
                ('device_user_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('response_payload', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Biometric Device Command',
                'verbose_name_plural': 'Biometric Device Commands',
                'ordering': ['status', 'queued_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricRawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('heartbeat', 'Heartbeat'), ('attendance', 'Attendance'), ('command_poll', 'Command Poll'), ('command_ack', 'Command Ack'), ('user_snapshot', 'User Snapshot'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('remote_ip', models.CharField(blank=True, max_length=45)),
                ('device_user_id', models.CharField(blank=True, max_length=64)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.TextField(blank=True)),
                ('parsed_ok', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Biometric Raw Event',
                'verbose_name_plural': 'Biometric Raw Events',
                'ordering': ['-event_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceUserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_type', models.CharField(blank=True, choices=[('member', 'Member'), ('staff', 'Staff')], max_length=12)),
                ('device_user_id', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Device User Link',
                'verbose_name_plural': 'Device User Links',
                'ordering': ['device_user_id'],
            },
        ),
        migrations.CreateModel(
            name='MemberBiometricDeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_user_id', models.CharField(blank=True, help_text='Device user ID (PIN/UID) for this member, copied from Member.device_user_id.', max_length=64)),
                ('is_enabled_on_device', models.BooleanField(default=False, help_text='Whether this member is currently enabled or active on this device.')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Device'), ('success', 'Synced Successfully'), ('failed', 'Failed')], default='pending', help_text='Overall biometric sync status for this member on this device.', max_length=20)),
                ('face_added', models.BooleanField(default=False)),
                ('fingerprint_added', models.BooleanField(default=False)),
                ('password_added', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Member Biometric Device Status',
                'verbose_name_plural': 'Member Biometric Device Statuses',
                'ordering': ['device', 'member'],
            },
        ),
        migrations.CreateModel(
            name='StaffBiometricDeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_user_id', models.CharField(blank=True, help_text='Device user ID (PIN/UID) for this staff member, copied from Staff.device_user_id.', max_length=64)),
                ('is_enabled_on_device', models.BooleanField(default=False)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Device'), ('success', 'Synced Successfully'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('face_added', models.BooleanField(default=False)),
                ('fingerprint_added', models.BooleanField(default=False)),
                ('password_added', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Staff Biometric Device Status',
                'verbose_name_plural': 'Staff Biometric Device Statuses',
                'ordering': ['device', 'staff'],
            },
        ),
        migrations.AlterModelOptions(
            name='biometricdevice',
            options={'ordering': ['device_name', 'serial_number'], 'verbose_name': 'Biometric Device', 'verbose_name_plural': 'Biometric Devices'},
        ),
        migrations.RenameField(
            model_name='attendancelog',
            old_name='device_id',
            new_name='device_identifier',
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='attendance.biometricdevice'),
        ),
        migrations.AlterField(
            model_name='biometricsynclog',
            name='action',
            field=models.CharField(choices=[('device_heartbeat', 'Device Heartbeat'), ('access_attempt', 'Access Attempt'), ('enrollment', 'Enrollment'), ('device_sync', 'Device Sync'), ('conflict', 'Conflict'), ('command', 'Command'), ('raw_event', 'Raw Event')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['date', 'person_type'], name='attendance__date_48eeb9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['device_user_id', 'date'], name='attendance__device__f763e8_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['member', 'date'], name='attendance__member__089966_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['staff', 'date'], name='attendance__staff_i_6b1806_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricsynclog',
            index=models.Index(fields=['action', '-created_at'], name='attendance__action_f0d5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricsynclog',
            index=models.Index(fields=['device_user_id', '-created_at'], name='attendance__device__521e28_idx'),
        ),
        migrations.AddField(
            model_name='biometricdevicecommand',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='attendance.biometricdevice'),
        ),
        migrations.AddField(
            model_name='biometricdevicecommand',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_commands', to='members.member'),
        ),
        migrations.AddField(
            model_name='biometricdevicecommand',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_commands', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='biometricrawevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_events', to='attendance.biometricdevice'),
        ),
        migrations.AddField(
            model_name='deviceuserlink',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_links', to='members.member'),
        ),
        migrations.AddField(
            model_name='deviceuserlink',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_links', to='staffs.staff'),
        ),
        migrations.AddField(
            model_name='memberbiometricdevicestatus',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_statuses', to='attendance.biometricdevice'),
        ),
        migrations.AddField(
            model_name='memberbiometricdevicestatus',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_statuses', to='members.member'),
        ),
        migrations.AddField(
            model_name='staffbiometricdevicestatus',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_statuses', to='attendance.biometricdevice'),
        ),
        migrations.AddField(
            model_name='staffbiometricdevicestatus',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_statuses', to='staffs.staff'),
        ),
        migrations.AddIndex(
            model_name='biometricdevicecommand',
            index=models.Index(fields=['device', 'status', 'queued_at'], name='attendance__device__263873_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricdevicecommand',
            index=models.Index(fields=['device_user_id', 'status'], name='attendance__device__cfc11f_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricdevicecommand',
            index=models.Index(fields=['person_type', 'status'], name='attendance__person__b886e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='biometricdevicecommand',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('member__isnull', False), ('staff__isnull', True)), models.Q(('member__isnull', True), ('staff__isnull', False)), _connector='OR'), name='biometric_command_exactly_one_person'),
        ),
        migrations.AddIndex(
            model_name='biometricrawevent',
            index=models.Index(fields=['event_type', '-event_time'], name='attendance__event_t_2ff222_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricrawevent',
            index=models.Index(fields=['device_user_id', '-event_time'], name='attendance__device__162193_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceuserlink',
            index=models.Index(fields=['device_user_id', 'is_active'], name='attendance__device__730cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceuserlink',
            index=models.Index(fields=['person_type', 'is_active'], name='attendance__person__bbc541_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceuserlink',
            constraint=models.UniqueConstraint(fields=('device_user_id',), name='unique_device_user_link_device_user_id'),
        ),
        migrations.AddConstraint(
            model_name='deviceuserlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('member__isnull', False), ('staff__isnull', True)), models.Q(('member__isnull', True), ('staff__isnull', False)), _connector='OR'), name='device_user_link_exactly_one_person'),
        ),
        migrations.AddIndex(
            model_name='memberbiometricdevicestatus',
            index=models.Index(fields=['device', 'sync_status'], name='attendance__device__228fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='memberbiometricdevicestatus',
            index=models.Index(fields=['member', 'sync_status'], name='attendance__member__cb0da3_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberbiometricdevicestatus',
            constraint=models.UniqueConstraint(fields=('member', 'device'), name='unique_member_biometric_device_status'),
        ),
        migrations.AddIndex(
            model_name='staffbiometricdevicestatus',
            index=models.Index(fields=['device', 'sync_status'], name='attendance__device__39710b_idx'),
        ),
        migrations.AddIndex(
            model_name='staffbiometricdevicestatus',
            index=models.Index(fields=['staff', 'sync_status'], name='attendance__staff_i_62f18a_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffbiometricdevicestatus',
            constraint=models.UniqueConstraint(fields=('staff', 'device'), name='unique_staff_biometric_device_status'),
        ),
    ]
